### ISSUE TITLE
C/CXXFLAGS not overwritten / extended

### ISSUE THREAD

**Issue by wolfv** [conda-forge/clang-compiler-activation-feedstock#125]
### Comment:

If I understand correctly, the activation scripts currently use an existing `CXXFLAGS` / `CFLAGS` variable instead of overwriting.

I wanted to inject a `-fdiagnostic-colors=always` flag for better output in `rattler-build`. Would you be open to a PR that either reacts on an existing variable like `CLICOLOR_FORCE` or adds `CXXFLAGS_EXTENSION`?

**Comment by isuruf** [comment]
We should do the same as https://github.com/conda-forge/ctng-compiler-activation-feedstock/blob/main/recipe/activate-gcc.sh#L176-L178

**Comment by h-vetinari** [comment]
Since the main branch moved on, here are the [lines](https://github.com/conda-forge/ctng-compiler-activation-feedstock/blob/fecc9f3195ba0506c6b2a08f188058a8c9bd0561/recipe/activate-gcc.sh#L176-L178) this was referring to
