### ISSUE TITLE
clang -fuse-ld=lld failed

### ISSUE THREAD

**Issue by SwordTechCorp** [conda-forge/clang-compiler-activation-feedstock#145]
### Comment:

Hello! I'm trying to build a project within micromamba environment. I've installed the following: `lld`,`clang`,`clangxx`,`cmake`,`ninja`

Not sure if it is an issue with lld or clang. The following error pops up when I execute `clang -fuse-ld=lld in.c` 
```
ld.lld: error: cannot open /lib64/libc.so.6: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
But the following command is working correctly `gcc -fuse-ld=lld in.c` 

I tried to append `--sysroot $CONDA_PREFIX` but that resulted in missing other files.

**Comment by h-vetinari** [comment]
Can you please fill out the entire issue template, including the output of `conda list` and `conda info`?

> I tried to append `--sysroot $CONDA_PREFIX` but that resulted in missing other files.

To be able to use the sysroot in the environment, you'll need something like:
```
--sysroot ${PREFIX}/x86_64-conda-linux-gnu/sysroot
```
but also ensure that `sysroot_linux-64` is installed (if you're on an x64 system; otherwise `sysroot_linux-aarch64` etc.)

**Comment by SwordTechCorp** [comment]
> Can you please fill out the entire issue template, including the output of `conda list` and `conda info`?
> 
> > I tried to append `--sysroot $CONDA_PREFIX` but that resulted in missing other files.
> 
> To be able to use the sysroot in the environment, you'll need something like:
> 
> ```
> --sysroot ${PREFIX}/x86_64-conda-linux-gnu/sysroot
> ```
> 
> but also ensure that `sysroot_linux-64` is installed (if you're on an x64 system; otherwise `sysroot_linux-aarch64` etc.)

Thank you so much! Sorry I didn't find the template at the first place.

You are right! By appending `--sysroot ${PREFIX}/x86_64-conda-linux-gnu/sysroot` , the command works! However, I suppose without `--sysroot`, lld should be working as well.

I'm using micromamba actually.

#### Version Info
micromamba list output:
            environment : clanglld (active)
           env location : /home/user/micromamba/envs/clanglld
      user config files : /home/user/.mambarc
 populated config files : 
       libmamba version : 1.4.3
     micromamba version : 1.4.3
           curl version : libcurl/7.88.1 OpenSSL/3.1.0 zlib/1.2.13 zstd/1.5.2 libssh2/1.10.0 nghttp2/1.52.0
     libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       virtual packages : __unix=0=0
                          __linux=5.14.0=0
                          __glibc=2.31=0
                          __archspec=1=x86_64
               channels : 
       base environment : /home/user/micromamba
               platform : linux-64

micromamba list output :
  Name                     Version  Build               Channel    
─────────────────────────────────────────────────────────────────────
  _libgcc_mutex            0.1      conda_forge         conda-forge
  _openmp_mutex            4.5      2_gnu               conda-forge
  binutils_impl_linux-64   2.43     h4bf12b8_1          conda-forge
  clang                    19.1.1   default_h9e3a008_0  conda-forge
  clang-19                 19.1.1   default_hb5137d0_0  conda-forge
  icu                      75.1     he02047a_0          conda-forge
  kernel-headers_linux-64  3.10.0   he073ed8_17         conda-forge
  ld_impl_linux-64         2.43     h712a8e2_1          conda-forge
  libclang-cpp19.1         19.1.1   default_hb5137d0_0  conda-forge
  libgcc                   14.1.0   h77fa898_1          conda-forge
  libgcc-devel_linux-64    14.1.0   h5d3d1c9_101        conda-forge
  libgcc-ng                14.1.0   h69a702a_1          conda-forge
  libgomp                  14.1.0   h77fa898_1          conda-forge
  libiconv                 1.17     hd590300_2          conda-forge
  libllvm19                19.1.1   ha7bfdaf_0          conda-forge
  libstdcxx                14.1.0   hc0a3c3a_1          conda-forge
  libstdcxx-ng             14.1.0   h4852527_1          conda-forge
  libxml2                  2.12.7   he7c6b58_4          conda-forge
  libzlib                  1.3.1    hb9d3cd8_2          conda-forge
  lld                      19.1.1   ha85224e_0          conda-forge
  sysroot_linux-64         2.17     h4a8ded7_17         conda-forge
  tzdata                   2024b    hc8b5060_0          conda-forge
  xz                       5.2.6    h166bdaf_0          conda-forge
  zstd                     1.5.6    ha6fb4c9_0          conda-forge

#### To Reproduce
Starting from a clean micromamba environment

```
micromamba install -c conda-forge lld clang
clang -fuse-ld=lld in.c
```
where `in.c` is a simple C source.

**Comment by h-vetinari** [comment]
Can you please provide the actual error that happens without the `--sysroot` argument?

**Comment by SwordTechCorp** [comment]
Thank you for the response! I get the following message after I run `clang -fuse-ld=lld in.c -v`
```
clang version 19.1.1 (https://github.com/conda-forge/clangdev-feedstock 7d84e3a207c1d5abcfa695bbe3f16e88fcd713cb)
Target: x86_64-conda-linux-gnu
Thread model: posix
InstalledDir: /home/user/micromamba/envs/clanglld/bin
Found candidate GCC installation: /home/user/micromamba/envs/clanglld/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0
Selected GCC installation: /home/user/micromamba/envs/clanglld/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/home/user/micromamba/envs/clanglld/bin/clang-19" -cc1 -triple x86_64-conda-linux-gnu -emit-obj -dumpdir a- -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name t.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=/home/user/framework/scalehls-hida -v -fcoverage-compilation-dir=/home/user/framework/scalehls-hida -resource-dir /home/user/micromamba/envs/clanglld/lib/clang/19 -internal-isystem /home/user/micromamba/envs/clanglld/lib/clang/19/include -internal-isystem /home/user/micromamba/envs/clanglld/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0/../../../../x86_64-conda-linux-gnu/sysroot/usr/local/include -internal-isystem /home/user/micromamba/envs/clanglld/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0/../../../../x86_64-conda-linux-gnu/include -internal-externc-isystem /home/user/micromamba/envs/clanglld/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0/../../../../x86_64-conda-linux-gnu/sysroot/include -internal-externc-isystem /home/user/micromamba/envs/clanglld/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0/../../../../x86_64-conda-linux-gnu/sysroot/usr/include -fdeprecated-macro -ferror-limit 19 -fmessage-length=167 -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/t-874c92.o -x c++ t.cpp
clang -cc1 version 19.1.1 based upon LLVM 19.1.1 default target x86_64-conda-linux-gnu
ignoring nonexistent directory "/home/user/micromamba/envs/clanglld/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0/../../../../x86_64-conda-linux-gnu/sysroot/usr/local/include"
ignoring nonexistent directory "/home/user/micromamba/envs/clanglld/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0/../../../../x86_64-conda-linux-gnu/include"
ignoring nonexistent directory "/home/user/micromamba/envs/clanglld/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0/../../../../x86_64-conda-linux-gnu/sysroot/include"
#include "..." search starts here:
#include <...> search starts here:
 /home/user/micromamba/envs/clanglld/lib/clang/19/include
 /home/user/micromamba/envs/clanglld/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0/../../../../x86_64-conda-linux-gnu/sysroot/usr/include
End of search list.
 "/home/user/micromamba/envs/clanglld/bin/ld.lld" -z relro --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -pie -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o a.out /home/user/micromamba/envs/clanglld/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0/../../../../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib64/Scrt1.o /home/user/micromamba/envs/clanglld/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0/../../../../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib64/crti.o /home/user/micromamba/envs/clanglld/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0/crtbeginS.o -L/home/user/micromamba/envs/clanglld/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0 -L/home/user/micromamba/envs/clanglld/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0/../../../../x86_64-conda-linux-gnu/sysroot/lib/../lib64 -L/home/user/micromamba/envs/clanglld/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0/../../../../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib64 -L/home/user/micromamba/envs/clanglld/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0/../../../../x86_64-conda-linux-gnu/lib -L/home/user/micromamba/envs/clanglld/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0/../../../../x86_64-conda-linux-gnu/sysroot/lib -L/home/user/micromamba/envs/clanglld/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0/../../../../x86_64-conda-linux-gnu/sysroot/usr/lib /tmp/t-874c92.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /home/user/micromamba/envs/clanglld/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0/crtendS.o /home/user/micromamba/envs/clanglld/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0/../../../../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib64/crtn.o
ld.lld: error: cannot open /lib64/libc.so.6: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by h-vetinari** [comment]
One thing I notice is that you have a _very_ old micromamba version:
```
       libmamba version : 1.4.3
     micromamba version : 1.4.3
```
In particular, there was a [bug](https://github.com/mamba-org/mamba/issues/3423) until 1.5.9 that caused problems when installing
```
  libgcc                   14.1.0   h77fa898_1          conda-forge
  libgcc-ng                14.1.0   h69a702a_1          conda-forge
```
It's possible that your environment got corrupted due to that.

Please update your micromamba, create a fresh environment, and then report back if the problem still exists.

**Comment by SwordTechCorp** [comment]
Thanks for the information! @h-vetinari 
I've tried with the latest version of micromamba, as well as conda. Unfortunately, it appears that the same problem still exists. 

#### conda info
     active environment : clanglld
    active env location : /home/test/miniconda3/envs/clanglld
            shell level : 2
       user config file : /home/test/.condarc
 populated config files :
          conda version : 24.7.1
    conda-build version : not installed
         python version : 3.12.4.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen2
                          __conda=24.7.1=0
                          __glibc=2.39=0
                          __linux=6.8.0=0
                          __unix=0=0
       base environment : /home/test/miniconda3  (writable)
      conda av data dir : /home/test/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/test/miniconda3/pkgs
                          /home/test/.conda/pkgs
       envs directories : /home/test/miniconda3/envs
                          /home/test/.conda/envs
               platform : linux-64
             user-agent : conda/24.7.1 requests/2.32.3 CPython/3.12.4 Linux/6.8.0-45-generic ubuntu/24.04.1 glibc/2.39 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.8 aau/0.4.4 c/. s/. e/.
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
#### micromamba info
       libmamba version : 2.0.2
     micromamba version : 2.0.2
           curl version : libcurl/8.9.1 OpenSSL/3.3.2 zlib/1.3.1 zstd/1.5.6 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.4 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.6
       envs directories : /home/test/micromamba/envs
          package cache : /home/test/micromamba/pkgs
                          /home/test/.mamba/pkgs
            environment : base
           env location : /home/test/micromamba
      user config files : /home/test/.mambarc
 populated config files :
       virtual packages : __unix=0=0
                          __linux=6.8.0=0
                          __glibc=2.39=0
                          __archspec=1=x86_64_v3
               channels : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
       base environment : /home/test/micromamba
               platform : linux-64

**Comment by h-vetinari** [comment]
I think this is a fundamental difference between how RHEL-based distros (like our infrastructure) and Debian-based distros (like Ubuntu) are dealing with `libc`. RHEL derivatives have it under `/lib64/libc.so.6`, whereas ubuntu [has it](https://www.golinuxcloud.com/how-do-i-install-the-linux-library-libc-so-6/) under something like `/lib/x86_64-linux-gnu/libc.so.6`.

If you want to use our clang (+lld) on an Ubuntu-like distro, the easiest might be to create a symlink like[^1]:
```
sudo ln -s /lib/x86_64-linux-gnu/libc.so.6 /lib64/libc.so.6
```
The alternative would be that we'd need to teach our `ld.lld` to look into our sysroot by default. Not sure if that's possible or indeed if we'd wish to do that (lld currently does not depend on the sysroot; presumably that would be OK though, as it'll always be there when using a compiler, and using `lld` without compiler is not really a thing I think). CC @isuruf

[^1]: funnily enough, Ubuntu already has a symlink `ld-linux-x86-64.so.2 -> ../lib/x86_64-linux-gnu/ld-linux-x86-64.so.2` under `lib64`, which is doing the exact same thing for the dynamic linker.

**Comment by isuruf** [comment]
> I think this is a fundamental difference between how RHEL-based distros (like our infrastructure) and Debian-based distros (like Ubuntu) are dealing with libc

That's not true.

The issue is because lld not using sysroot when using the libc.so linker script.

**Comment by h-vetinari** [comment]
> The issue is because lld not using sysroot when using the libc.so linker script.

Is this something we can fix on the lld side, or is this out of our control (i.e. in the distro-bits)?

**Comment by h-vetinari** [comment]
Ping @isuruf

**Comment by h-vetinari** [comment]
Thanks!
