### ISSUE TITLE
Using C++17

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/clang-compiler-activation-feedstock#17]
It looks like we are currently [requiring C++14 on macOS]( https://github.com/conda-forge/clang-compiler-activation-feedstock/blob/de9142c89e4da28b4d5eabd2bd6c9f0d84e6fa64/recipe/build.sh#L7 ); whereas, we use [C++17 on Linux]( https://github.com/conda-forge/ctng-compiler-activation-feedstock/blob/eac83f495f22488f449ff6c564e000105f9c8346/recipe/conda_build_config.yaml#L30 ). Would it be possible to start using C++17 on macOS as well?

**Comment by chrisburr** [comment]
I thought we were doing this already 😄 

@conda-forge/clang-compiler-activation Are there any objections to changing macOS to use C++17 by default or should I prepare the PR?

**Comment by jakirkham** [comment]
I'd take silence here as no objections Chris. Do you want to submit a PR? 🙂

**Comment by isuruf** [comment]
This needs to be co-ordinated with a boost update as changing the C++ standard changes boost ABI.

**Comment by jakirkham** [comment]
So we would piggy back on a Boost update and subsequent pinning migrator? That makes sense. Shouldn't be too difficult then. Are there any other issues you foresee?

**Comment by jakirkham** [comment]
Looking at past Boost version history, it seems like a new release is probably due around April.

**Comment by isuruf** [comment]
I don't think we should update the C++ version and remove the `-std=c++14` flag altogether from `CXXFLAGS` env variable.

**Comment by jakirkham** [comment]
Went ahead and put this on the agenda for tomorrow so we can figure out how we want to handle this

**Comment by xhochy** [comment]
@jakirkham @isuruf What was the outcome of the core meeting on this?

**Comment by jakirkham** [comment]
If that's true, we are planning to drop `-std=c++14` from `CXXFLAGS` as Isuru noted above

**Comment by xhochy** [comment]
**It actually does change!**

I've built `boost-cpp` once with `-std=c++14` and once with `-std=c++17` and it revealed the following ABI differences:

Script:
```python
from pathlib import Path
from subprocess import check_output

for lib_14 in list(Path("cxx14/lib").glob("*.dylib")):
    lib_17 = Path("cxx17") / "lib" / lib_14.name
    exports_14 = {line.split(b" ")[2] for line in check_output(f"nm {lib_14}", shell=True).split(b"\n") if b" " in line}
    exports_17 = {line.split(b" ")[2] for line in check_output(f"nm {lib_17}", shell=True).split(b"\n") if b" " in line}
    if exports_14 != exports_17:
        print(lib_14.name)
        print("-" * len(lib_14.name))
        print(exports_14 - exports_17)
        print(exports_17 - exports_14)
        print()
```

Output:

```
libboost_locale.dylib
---------------------
{b'__ZN5boost6locale4util23create_simple_converterERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE', b'__ZN5boost6locale4util21create_utf8_converterEv', b'__ZN5boost6locale28localization_backend_manager11add_backendERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS2_8auto_ptrINS0_20localization_backendEEE', b'__ZN5boost6locale4util14create_codecvtERKNSt3__16localeENS2_8auto_ptrINS1_14base_converterEEEj', b'__ZNK5boost6locale28localization_backend_manager3getEv'}
set()

libboost_context.dylib
----------------------
{b'__ZNSt3__117__call_once_proxyINS_5tupleIJRFvP6rlimitEOS3_EEEEEvPv', b'__ZNSt3__117__call_once_proxyINS_5tupleIJRFvPmEOS2_EEEEEvPv'}
{b'__ZNSt3__117__call_once_proxyINS_5tupleIJRDoFvP6rlimitEOS3_EEEEEvPv', b'__ZNSt3__117__call_once_proxyINS_5tupleIJRDoFvPmEOS2_EEEEEvPv'}
```

**Comment by jakirkham** [comment]
That's unfortunate. Probably no way to know this, but are those symbols actually used externally or are they just used by Boost?

**Comment by xhochy** [comment]
This stalled for quite some while but we increasingly see packages that require e.g. a C++17 enabled build of `abseil-cpp`. If someone can list todos, then I would look a bit into doing this; I'm currently out of ideas and would default to just remove `std=c++14` from the flags and then see what breaks.

**Comment by isuruf** [comment]
Can you run your script above with the latest version?

**Comment by jakirkham** [comment]
Meaning this ( https://github.com/conda-forge/clang-compiler-activation-feedstock/issues/17#issuecomment-846188588 )

Yeah can build with each flag locally and then compare :)

**Comment by BastianZim** [comment]
@jakirkham 
Ok am now more awake. :)
My understanding is that I first need to change this feedstock and then use this feedstock to build boost, is that incorrect? That's why I had initially assumed that it would be too difficult for me.

If I can just set the flags when building the boost feedstock and they are respected I can definitely do that.

**Comment by BastianZim** [comment]
🤦‍♂️ Looking in the right folder actually helps, who knew?

Small problem though because I'm unable to build with OSX, only Linux works. The former fails with `MacOSX10.9.sdk/usr/share/man/man8/setregion.8: Failed to create dir 'MacOSX10.9.sdk'` and I currently don't have a different machine to access and try.

**Comment by jakirkham** [comment]
> Are you sure? Because I thought you'd be interested in whenever it changes on OSX. Linux should also have changes, I would assume, but I'm not sure if they're the same as on OSX.

I mean there could be differences between how GCC on Linux and Clang on macOS do things. For example their name mangling may differ. That said, mainly we are looking for the existence of differences (not exactly how the symbol names are spelled). So I think just testing on Linux should be ok. We already use this as a guiding principle in how we do pinnings now.

**Comment by BastianZim** [comment]
Built everything but I think there is a misunderstanding somewhere on my part because it's not working.

Here is what I did:

1. Cloned https://github.com/conda-forge/boost-cpp-feedstock
2. Added flags based on https://github.com/conda-forge/clang-compiler-activation-feedstock/issues/17#issuecomment-947939069
3. Ran `python build-locally.py`
4. Searched `build_artifacts`

The only `.dylib` file I could find is `app-map-tidylib.md` (This is searching the whole `build_artifacts` folder).

Happy to continue and appreciate the help but we might hit a point where teaching me how to do it takes more work than building it... 😄

**Comment by jakirkham** [comment]
Yeah `src_cache` is just where conda-build downloads the source code and extracts it. We would want to look inside a directory called `linux-64`

Sounds good. Have a good night. Also thanks for all of your hard work today 😄

**Comment by BastianZim** [comment]
Ahh yeah that explains what it's called source cache... 😄 Ok that clears it up. 
I compared `build_artifacts_14/src_cache/boost_1_77_0` to `build_artifacts_14/linux-64/boost-cpp-1.77.0-h312852a_0/include/boost` because the script mentioned a `cxx14` folder that only exists in these and couldn't find difference but you're talking about `build_artifacts_14/linux-64/boost-cpp-1.77.0-h312852a_0/lib`.

iCloud didn't like the files so I have to rebuild them again but now I know where to look!

Thanks. And thanks for your patience...

**Comment by BastianZim** [comment]
@jakirkham Any news?

**Comment by jakirkham** [comment]
Sorry not following. What's the question?

**Comment by BastianZim** [comment]
My findings in https://github.com/conda-forge/clang-compiler-activation-feedstock/issues/17#issuecomment-948654331 based on what we had discussed above.

**Comment by jakirkham** [comment]
Right one thing I think we should check (and was meaning to do this, but haven't had a chance) is verify the libraries built used the C++ version we expect (IOW Boost didn't disregard compile flags we gave it). That said, it may [not obvious from rudimentary inspection]( https://stackoverflow.com/a/63575471 ). Though it may be possible [to record the flags in the libraries]( https://stackoverflow.com/a/33407404 ) and verify that way.

**Comment by jakirkham** [comment]
Another way to approach the problem above would be to look for any symbols that Boost includes with specific C++ versions. For example [`std::invoke`]( https://en.cppreference.com/w/cpp/utility/functional/invoke ) would be [one of these on C++17]( https://github.com/boostorg/context/blob/8289091f52da65422b6795d58295dea5fd9297c6/include/boost/context/detail/apply.hpp#L18-L20 ). It should be absent in C++14

**Comment by BastianZim** [comment]
`boost/context/detail/invoke.hpp` is unfortunately available in both.

**Comment by jakirkham** [comment]
Think it just copies all the headers no matter what. So don't think that would change based on C++ standard used

What we would want to check is [`nm`]( https://opensource.com/article/20/4/linux-binary-analysis ) on a relevant library (perhaps like the one above) to see if they are getting C++17 symbols in that case

If we can confirm that, this should help give us some confidence that Boost built how we expected and indeed the ABI/API surface hasn't changed between C++ standards

**Comment by BastianZim** [comment]
Ok, so `diff -qr /boost/build_artifacts_14/linux-64/boost-cpp-1.77.0-h312852a_0/include/boost /boost/build_artifacts_17/linux-64/boost-cpp-1.77.0-h312852a_1/include/boost` gave no results. I'll try rebuilding it with `-frecord-gcc-switches` based on your comment.

**Comment by jakirkham** [comment]
Would try `CFLAGS` and `CXXFLAGS`. Or is that what you tried already?

**Comment by BastianZim** [comment]
Ahh `CXXFLAGS` worked, thanks.

Using `strings` I get the following:

```zsh
strings /boost-cpp-feedstock/build_artifacts/linux-64/boost-cpp-1.77.0-h312852a_1/lib/libboost_chrono.so|grep "c++17"     
-std=c++17
```

`c++14` gives me nothing.

Do note though that I'm using a Mac here to read Linux files, not sure if something gets mangled along the way. 😄

**Comment by BastianZim** [comment]
@jakirkham Anything else that should be checked?

**Comment by jakirkham** [comment]
Not atm. @isuruf @xhochy do you have any more thoughts/questions/concerns here?

**Comment by BastianZim** [comment]
Just a super gentle ping here, as I'd need this for a feedstock - thanks!

**Comment by isuruf** [comment]
? Individual feedstocks can use C++17 if they want

**Comment by BastianZim** [comment]
I need it for `or-tools` which depends on `abseil-cpp` where I was directed to this issue by @xhochy.

Ref: https://github.com/conda-forge/staged-recipes/pull/16147#discussion_r708339730

**Comment by isuruf** [comment]
Why does `or-tools` and `abseil-cpp` need to have the same C++ language version?

**Comment by xhochy** [comment]
`abseil-cpp` does have a varying API based on whether it was compiled with C++17 or not (mostly around string views)

**Comment by isuruf** [comment]
So, that can be changed only when there's a new `abseil-cpp` I guess?

**Comment by xhochy** [comment]
Yes, there is a release outstanding: https://github.com/conda-forge/abseil-cpp-feedstock/pull/24

**Comment by h-vetinari** [comment]
OK, since the conclusion of this thread wasn't clear (to me), I repeat what @jakirkham noted in the vc-issue:
> At least with macOS and Linux, we dropped these flags ( [conda-forge/clang-compiler-activation-feedstock#75](https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/75) ) to leave it up to recipes.
