### ISSUE TITLE
Dont't set CODESIGN_ALLOCATE in activate-clang.sh

### ISSUE THREAD

**Issue by phil-blain** [conda-forge/clang-compiler-activation-feedstock#18]
Issue: this line in the activation script https://github.com/conda-forge/clang-compiler-activation-feedstock/blob/dec68237067572864e79a186082001017556daab/recipe/activate-clang.sh#L117 causes `CODESIGN_ALLOCATE` to be set to the version in the conda environment (ex. `/Users/Philippe/Logiciels/miniconda3/conda-bld/gdb_1590596079611/_build_env/bin/x86_64-apple-darwin13.4.0-codesign_allocate`)

This prevents using the system `codesign` to sign executables created by conda-build (which will be required to test https://github.com/conda-forge/gdb-feedstock/pull/23 in the CI.)

See https://github.com/conda-forge/gdb-feedstock/pull/23#issuecomment-634854735.

**Comment by isuruf** [comment]
If you want to use the system tool, you should unset this environment variable. Or better yet use the one that we ship.

**Comment by isuruf** [comment]
Feel free to reopen if you think this should be reopened.

**Comment by phil-blain** [comment]
thanks @isuruf. In fact I don't have permission to reopen.

I don't mind unsetting the variable, but it took me quite sometime to understand why `codesign` did not work during the conda-build process so I thought it was better to fix the issue here.

To quote the `codesign` man page (emphasis added):

> ENVIRONMENT
     If the CODESIGN_ALLOCATE environment variable is set, it identifies a substitute codesign_allocate tool used to allocate space for code signatures in Mach-O
     binaries. This is used by Xcode SDK distributions to provide architectural support for non-native platforms such as iPhones.  **The system will not accept
     such substitutes unless they are specially signed (by Apple)**.

So just having this variable sets breaks `codesign` since the `codesign_allocate` in this here package is surely not signed by Apple...

So I'm not sure what you mean by "use the one that we ship", I want to use `codesign` and conda-forge does not ship `codesign`.
